# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='IP \u0430\u0434\u0440\u0435\u0441')),
                ('port', models.IntegerField(verbose_name='\u043f\u043e\u0440\u0442')),
                ('timeout', models.IntegerField(verbose_name='\u0442\u0430\u0439\u043c\u0430\u0443\u0442 \u0441\u0435\u043a.')),
                ('serial', models.CharField(max_length=255, verbose_name='\u0441\u0435\u0440\u0438\u0439\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440')),
                ('phone', models.CharField(max_length=255, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('sim', models.CharField(max_length=255, verbose_name='\u043d\u043e\u043c\u0435\u0440 SIM \u043a\u0430\u0440\u0442\u044b')),
                ('protocol', models.CharField(choices=[(b'ce206', b'Energomera CE 206'), (b'iec61107', b'IEC 61107'), (b'mercury206', b'Mercury 206')], max_length=30, verbose_name='\u043f\u0440\u043e\u0442\u043e\u043a\u043e\u043b')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Address', verbose_name='\u0430\u0434\u0440\u0435\u0441')),
            ],
            options={
                'verbose_name': '\u043c\u043e\u0434\u0435\u043b\u044c \u043e\u0431\u043e\u0440\u0443\u0434\u043e\u0432\u0430\u043d\u0438\u044f',
                'verbose_name_plural': '\u043c\u043e\u0434\u0435\u043b\u0438 \u043e\u0431\u043e\u0440\u0443\u0434\u043e\u0432\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u043c\u043e\u0434\u0435\u043b\u044c',
                'verbose_name_plural': '\u043c\u043e\u0434\u0435\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u0438',
            },
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counters.Vendor', verbose_name='\u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='counter',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counters.EquipmentModel', verbose_name='\u0441\u0447\u0451\u0442\u0447\u0438\u043a'),
        ),
    ]
